DotNet4Neo4j/Neo4jClient

Neo4jClient/GraphClient.cs
Neo4jClient/Neo4jClient.csproj
Neo4jClient/Neo4jClient.nuspec
Neo4jClient/packages.config
Test/Test.csproj
Test/packages.config

This is sort of the ground work for #101.
- Upgraded to .NET 4.5
- Fixed the dependency package target frameworks as .NET 4.5
- Made the minimal changes to replace `ContinueWith` with `async` and `await` without changing the behavior.

Upgraded to .NET 4.5

---

Neo4jClient.Tests/Cypher/CypherFluentQueryDetachDeleteTests.cs
Neo4jClient.Tests/Neo4jClient.Tests.csproj
Neo4jClient/Cypher/CypherFluentQuery.cs
Neo4jClient/Cypher/ICypherFluentQuery.cs

You can now `.DetachDelete` from the client.
Fixes #129

Adds the ability to DETACH DELETE

---

Neo4jClient.Tests/Serialization/CustomJsonDeserializerTests.cs
Neo4jClient/Serialization/CommonDeserializerMethods.cs

Matching the way the Serialization works.

Deserialization uses CustomJsonConverters first

---

Neo4jClient.Tests/Cypher/CypherFluentQueryTests.cs
Neo4jClient/Cypher/CypherFluentQuery.cs
Neo4jClient/Cypher/CypherFluentQuery`TResult.cs

Now generates DESC clause for each field.
Fix problem with OrderByDescending generation from issue https://github.com/Readify/Neo4jClient/issues/145

Change OrderByDescending query generation

---

Neo4jClient.Tests/Cypher/CypherFluentQueryTests.cs
Neo4jClient/Cypher/CypherFluentQuery.cs
Neo4jClient/Cypher/CypherFluentQuery`TResult.cs
Neo4jClient/Cypher/ICypherFluentQuery.cs
Neo4jClient/Cypher/ICypherFluentQuery`TResult.cs
Neo4jClient/Cypher/IOrderedCypherFluentQuery.cs
Neo4jClient/Cypher/IOrderedCypherFluentQuery`TResult.cs
Neo4jClient/Cypher/QueryWriter.cs
Neo4jClient/Neo4jClient.csproj

Added IOrderedCypherFluentQuery for working with new order methods ThenBy and ThenByDescending for resolving that issue https://github.com/Readify/Neo4jClient/issues/145

Added IOrderedCypherFluentQuery

---

Neo4jClient.Tests/Cypher/CypherQueryTests.cs
Neo4jClient.Tests/GraphClientTests/Cypher/ExecuteCypherTests.cs
Neo4jClient/Cypher/CypherQuery.cs
Neo4jClient/GraphClient.cs

Allow CypherQuery to have a null value for parameters (Merge)

---

Neo4jClient/Execution/ResponseBuilder.cs

Link to original issue https://github.com/Readify/Neo4jClient/issues/157

ResponseBuilder.PrepareAsync ConfigureAwait(false) added in case of taskFactory is null

---

Neo4jClient/Execution/ResponseBuilder.cs

Reverts Readify/Neo4jClient#158
Reverting for the moment as the changes break 4 of the tests regarding exception/event handling, so need to be done passing those.
My fault for not checking before merging :(

Revert "ResponseBuilder.PrepareAsync ConfigureAwait(false) added in case of taskFactory is null"

---

Neo4jClient.Tests/HttpClientWrapperTests.cs
Neo4jClient.Tests/Neo4jClient.Tests.csproj
Neo4jClient/HttpClient.cs

User can now specify the HttpClient as well as user/pass

Add overload to HttpClientWrapper to accept Client

---

Neo4jClient.Tests/Cypher/CypherFluentQueryCallTests.cs
Neo4jClient.Tests/Cypher/CypherFluentQueryYieldTests.cs
Neo4jClient.Tests/Neo4jClient.Tests.csproj
Neo4jClient/Cypher/CypherCapabilities.cs
Neo4jClient/Cypher/CypherFluentQuery.cs
Neo4jClient/Cypher/ICypherFluentQuery.cs
Neo4jClient/GraphClient.cs

Add Call and Yield to CypherFluentQuery

---

Neo4jClient.Full/Neo4jClient.Full.csproj
Neo4jClient.Full/packages.config
Neo4jClient.Shared/packages.config
Neo4jClient.Tests/Neo4jClient.Tests.csproj
Neo4jClient.Tests/packages.config
Neo4jClient.Vb.Tests/Neo4jClient.Vb.Tests.vbproj
Neo4jClient.Vb.Tests/packages.config
Neo4jClient.nuspec
README.md

Removed unnecessary libraries (Microsoft.Net.Http, Microsoft.Bcl, Microsoft.Bcl.Build) from dependencies.

Removed unnecessary libraries Microsoft.Net.Http, Microsoft.Bcl

---

Neo4jClient.Shared/Extensions/MemberInfoExtensions.cs
Neo4jClient.Tests/Cypher/CypherFluentQueryWhereTests.cs

Honour the NewtonSoft JsonObject NamingStrategy

---

Neo4jClient.Full/Neo4jClient.Full.csproj.DotSettings
Neo4jClient.Shared/Cypher/CypherFluentQuery.cs
Neo4jClient.Shared/Cypher/CypherFluentQueryAdvanced.cs
Neo4jClient.Shared/Cypher/ICypherFluentQueryAdvanced.cs
Neo4jClient.Tests/Cypher/CypherFluentQueryAdvancedTests.cs
Neo4jClient.Tests/Cypher/CypherFluentQuerySetClientTests.cs
Neo4jClient.Tests/Neo4jClient.Tests.csproj
Neo4jClient/Neo4jClient.csproj.DotSettings
Neo4jClient/Neo4jClient.nuget.targets

query.Advanced.SetClient(client)

Added ability to set client

---

Neo4jClient.nuspec

Ref #239
Bumped targetFramework from netstandard1.0 to netstandard1.1 since does not support netstandard1.0  (AFAIK).

Added ref to missing System.Diagnostics.DiagnosticSource

---

Neo4jClient.Shared/Cypher/CypherQuery.cs
Neo4jClient.Shared/GraphClient.cs
Neo4jClient.Shared/Neo4jDriverExtensions.cs
Neo4jClient.Tests.Shared/BoltGraphClientTests/BoltGraphClientTests.cs
Neo4jClient.Tests.Shared/Extensions/Neo4jDriverExtensionsTests.cs
Neo4jClient/Neo4jClient.nuget.targets

Fixes #249 
Also - did a bit of tidying up

Serializes DateTimes correctly

---

Neo4jClient.Shared/Neo4jDriverExtensions.cs
Neo4jClient.Tests.Shared/BoltGraphClientTests/BoltGraphClientTests.cs
Neo4jClient.Tests.Shared/Extensions/Neo4jDriverExtensionsTests.cs

Guids serialized `WithParams` correctly

---

Neo4jClient.Shared/StatementResultHelper.cs
Neo4jClient.Tests.Shared/BoltGraphClientTests/Cypher/ExecuteGetCypherResultsTests.cs

This fixes #260 
Includes two unit tests: one for defined types and another for anonymous types.

Fix Relationship Deserialization for Anonymous Types

---

Neo4jClient.FSharp.Tests/CypherFluentQueryTests.fs
Neo4jClient.FSharp.Tests/Neo4jClient.FSharp.Tests.fsproj
Neo4jClient.sln

Adds FSharp tests to the project

Adding a couple of FSharp Tests

---

Neo4jClient.Full/Neo4jClient.Full.csproj
Neo4jClient.Full/packages.config
Neo4jClient.Full452/Neo4jClient.Full452.csproj
Neo4jClient.Full452/packages.config
Neo4jClient.Tests.Core/Neo4jClient.Tests.Core.csproj
Neo4jClient.Tests.Shared/Cypher/CypherFluentQueryCreateUniqueTests.cs
Neo4jClient.Tests.Shared/NodeReferenceTests.cs
Neo4jClient.Tests.Shared/NodeTests.cs
Neo4jClient.Tests.Shared/RelationshipReferenceTests.cs
Neo4jClient.Tests.Shared/Serialization/CypherJsonDeserializerTests.cs
Neo4jClient.Tests/Neo4jClient.Tests.csproj
Neo4jClient.Tests/packages.config
Neo4jClient.Vb.Tests/Neo4jClient.Vb.Tests.vbproj
Neo4jClient.Vb.Tests/packages.config
Neo4jClient.nuspec
Neo4jClient/project.json

Allowing Neo4jClient to work on Azure Functions.

Reverting NewtonSoft.Json to 9.0.1

---

Neo4jClient.Shared/Neo4jDriverExtensions.cs
Neo4jClient.Shared/Serialization/CustomJsonSerializer.cs
Neo4jClient.Tests.Shared/Extensions/Neo4jDriverExtensionsTests.cs
Neo4jClient.Tests.Shared/Serialization/CustomJsonDeserializerTests.cs
Neo4jClient.Tests.Shared/Serialization/CustomJsonSerializerTests.cs

Allows custom serializers to be used on Bolt sessions as well.

Fixes #292

---

Neo4jClient.Tests/Cypher/CypherFluentQueryWhereTests.cs
Neo4jClient/Cypher/CypherFluentQuery`Where.cs
Neo4jClient/Cypher/CypherFluentQuery`WhereIf.cs
Neo4jClient/Cypher/ICypherFluentQuery`Where.cs
Neo4jClient/Cypher/ICypherFluentQuery`WhereIf.cs

Adding **WhereIf**, **OrWhereIf** and **AndWhereIf** will help to make some conditions before applying to the _**query text**_.

Adding WhereIf, OrWhereIf and AndWhereIf

---

Neo4jClient.Tests/BoltGraphClientTests/BoltGraphClientTests.cs
Neo4jClient.Tests/Neo4jClient.Tests.csproj
Neo4jClient.Vb.Tests/Neo4jClient.Vb.Tests.vbproj
Neo4jClient.sln
Neo4jClient/Neo4jDriverExtensions.cs

`BoltGraphClient` now takes consideration of the `CamelCaseJsonResolver`

Fixes #385

---

Neo4jClient.FSharp.Tests/Neo4jClient.FSharp.Tests.fsproj
Neo4jClient/Neo4jClient.csproj

Updated `Neo4j.Driver` to `4.2.0`

---

Neo4jClient/BoltGraphClient.cs
Neo4jClient/GraphClient.cs
Neo4jClient/Neo4jDriverExtensions.cs
Neo4jClient/Transactions/Bolt/BoltNeo4jTransaction.cs

I assume these calls works fine even though resuming on a different thread. If not, a comment should be added instead. At least all tests are still green locally.

Don't force resuming continuation on same thread

---

Neo4jClient.Tests/StatementResultHelperTests.cs
Neo4jClient/StatementResultHelper.cs

Added support for temporal Neo4J properties.

Support the TemporalValue.

---

Neo4jClient/BoltGraphClient.cs

Changes error message for AddressResolver overload

---

Neo4jClient.Tests/Cypher/CypherFluentQueryCallTests.cs

This also actually adds the `.Call` code to the release

Changes to tests to get AppVeyor to build properly

---

Neo4jClient.FSharp.Tests/Neo4jClient.FSharp.Tests.fsproj
Neo4jClient.Tests/Neo4jClient.Tests.csproj
Neo4jClient.Vb.Tests/Neo4jClient.Vb.Tests.vbproj
Neo4jClient/Neo4jClient.csproj

And some of the test references.
This is to hopefully resolve #421

Bumping Neo4j.Driver version

---

Neo4jClient.Tests/Cypher/CypherFluentQueryCallTests.cs
Neo4jClient/BoltGraphClient.cs
Neo4jClient/Cypher/CypherCapabilities.cs
Neo4jClient/Cypher/CypherFluentQuery.cs
Neo4jClient/Cypher/ICypherFluentQuery.cs
Neo4jClient/GraphClient.cs

Fixes #429
Adds `.InTransactions` as a call on the `ICypherFluentQuery` interface.

Adds support for `IN TRANSACTIONS`

---

Neo4jClient.Tests/Cypher/CypherFluentQueryWithParamTests.cs

Two tests were not updated to work with PR #437 
These have been fixed for deployment

Fixing tests to work with #436

---

Neo4jClient.FSharp.Tests/Neo4jClient.FSharp.Tests.fsproj
Neo4jClient.Tests/Neo4jClient.Tests.csproj
Neo4jClient.Vb.Tests/Neo4jClient.Vb.Tests.vbproj
Neo4jClient/Neo4jClient.csproj

Updating the packages to the most recent versions, this keeps the client aligned with the official driver

Neo4j Driver Update

---

Neo4jClient.Tests/BoltGraphClientTests/ConnectAsyncTests.cs
Neo4jClient/DriverWrapper.cs
Neo4jClient/Neo4jClient.csproj

Add the new interfaces that were added to the IResultCursor and IDriver in 5.5

Update Neo4j-Driver Version to 5.5

---

Neo4jClient.Tests/BoltGraphClientTests/BoltGraphClientTests.cs
Neo4jClient.Tests/BoltGraphClientTests/Cypher/ExecuteGetCypherResultsTests.cs
Neo4jClient.Tests/BoltTestHarness.cs
Neo4jClient.Tests/StatementResultHelperTests.cs
Neo4jClient/Neo4jClient.csproj
Neo4jClient/StatementResultHelper.cs

Adds support for the `5.18.1` version of the `Neo4j.Driver` to allow for a bug fix.

Upgrading to 5.18.1

---

Neo4jClient.Tests/Cypher/CypherFluentQueryPlannerTests.cs
Neo4jClient/BoltGraphClient.cs
Neo4jClient/Cypher/CypherCapabilities.cs
Neo4jClient/Cypher/CypherFluentQuery.cs
Neo4jClient/Cypher/CypherRuntime.cs
Neo4jClient/Cypher/ICypherFluentQuery.cs
Neo4jClient/GraphClient.cs

Adds support for runtime=
