- Neo4jClient/Cypher/CypherFluentQuery.cs
- Neo4jClient/Cypher/ICypherFluentQuery.cs
- Test/Cypher/CypherFluentQueryParserVersionTests.cs
Giving the ability to use things like `2.1.experimental`, fixes issue #73
client.ParserVersion("2.1.experimental").Match(/*etc*/);
results in:
CYPHER 2.1.experimental 
MATCH /*etc*/
> Adds the ability for a user to pass free text to the ParserVersion call

- Neo4jClient.Tests/Transactions/QueriesInTransactionTests.cs
- Neo4jClient/GraphClient.cs
Using a custom JsonContractResolver + TransactionScope causes failed deserialization
> Fix for issue #110 https://github.com/Readify/Neo4jClient/issues/110

- Neo4jClient.Tests/Transactions/TransactionManagementTests.cs
- Neo4jClient/Transactions/ITransactionManager.cs
- Neo4jClient/Transactions/TransactionManager.cs
- README.md
Instead of catching an InvalidOperationException, the stack is now
checked to see if it has any items before Pop / Peek calls are made.
> Check for Transaction Scope Stack being Empty

- Neo4jClient.Tests/Cypher/CypherFluentQueryPlannerTests.cs
- Neo4jClient.Tests/GraphClientTests/ConnectTests.cs
- Neo4jClient.Tests/MockResponse.cs
- Neo4jClient.Tests/Neo4jClient.Tests.csproj
- Neo4jClient.Tests/Neo4jClient.Tests.csproj.DotSettings
- Neo4jClient.Tests/RestTestHarness.cs
- Neo4jClient.Tests/Transactions/TransactionManagementTests.cs
- Neo4jClient/Cypher/CypherCapabilities.cs
- Neo4jClient/Cypher/CypherFluentQuery.cs
- Neo4jClient/Cypher/CypherFluentQuery`Return.cs
- Neo4jClient/Cypher/CypherFluentQuery`Where.cs
- Neo4jClient/Cypher/CypherFluentQuery`With.cs
- Neo4jClient/Cypher/CypherPlanner.cs
- Neo4jClient/Cypher/CypherQuery.cs
- Neo4jClient/Cypher/ICypherFluentQuery.cs
- Neo4jClient/GraphClient.cs
- Neo4jClient/Neo4jClient.csproj
- Neo4jClient/Neo4jClient.csproj.DotSettings
Adds the `.Planner` option to the client. (Fixes #115)
Planner can be set in two ways:
client.Cypher.Planner("IDP").Match(/*etc*/);
client.Cypher.Planner(CypherPlanner.CostIdp).Match(/*etc*/);
Both result in:
PLANNER IDP
MATCH //etc
> Add ability to set the Planner

- Neo4jClient.Tests/Cypher/CypherFluentQueryReturnTests.cs
- Neo4jClient.Tests/Cypher/CypherFluentQueryWhereTests.cs
- Neo4jClient.Tests/Cypher/CypherFluentQueryWithTests.cs
- Neo4jClient.Tests/Extensions/MemberInfoExtensionsTests.cs
- Neo4jClient.Tests/Neo4jClient.Tests.csproj
- Neo4jClient/Cypher/CypherReturnExpressionBuilder.cs
- Neo4jClient/Cypher/CypherWhereExpressionBuilder.cs
- Neo4jClient/Cypher/CypherWhereExpressionVisitor.cs
- Neo4jClient/Cypher/CypherWithExpressionBuilder.cs
- Neo4jClient/Extensions/MemberInfoExtensions.cs
- Neo4jClient/Neo4jClient.csproj
The Expression Visitors now read the `JsonProperty` attributes and take
them into account for generating the Cypher queries
> Expression Visitors take read JsonProperty

- Neo4jClient.Tests/Serialization/CypherJsonDeserializerTests.cs
- Neo4jClient/Serialization/CypherJsonDeserializer.cs
You can either merge from changeset: https://github.com/Readify/Neo4jClient/commit/7eff966a94019d525b682f2efea1c967f0e041fd
or changeset (my HEAD):
https://github.com/Readify/Neo4jClient/commit/290ed5d430e31278d8f61c38f3ae431b791e082f
The first fixes the bug. The second refactors to make test cases consistent with the rest of the file.
> bug in DateTime serialisation fixed.

- Neo4jClient.Tests/MockResponse.cs
- Neo4jClient.Tests/Neo4jClient.Tests.csproj
- Neo4jClient.Tests/RestTestHarness.cs
- Neo4jClient.Tests/Transactions/QueriesInTransactionTests.cs
- Neo4jClient.Tests/Transactions/TransactionManagementTests.cs
- Neo4jClient.Tests/Transactions/TransactionRestResponseHelper.cs
- Neo4jClient/Cypher/CypherCapabilities.cs
- Neo4jClient/Execution/ExecutionConfiguration.cs
- Neo4jClient/GraphClient.cs
- Neo4jClient/Transactions/Neo4jTransaction.cs
In 2.2.6+ of Neo4j any Cypher error was set to Rollback automatically.
This commit makes the client ignore a 404 response *only* if the version
of Neo4j is > 2.2.6 AND a Cypher Error has occurred. The 404 would still
be seen for a genuine timeout.
This will fix #127
> Timeout for 2.2.6+ is ignored if has errors

- Neo4jClient.Tests/Cypher/CypherFluentQueryWithTests.cs
- Neo4jClient/Cypher/CypherFluentQuery`With.cs
- Neo4jClient/Cypher/CypherWithExpressionBuilder.cs
Some of the flows in `.Where` are still suffixing properties with `?`, which is Cypher 1.9. There was nothing in the generation to respect the capability detection.
> Respect Cypher capability detection for null suffixes in WHERE clauses

- Neo4jClient/NeoException.cs
Currently NeoExceptions aren't serializable 'out of the box' and some systems that rely on Exceptions being serializable can't send NeoExceptions around.
> Make NeoException serializable

- Neo4jClient.Tests/Cypher/CypherQueryTests.cs
- Neo4jClient.Tests/GraphClientTests/Cypher/ExecuteCypherTests.cs
- Neo4jClient/Cypher/CypherQuery.cs
- Neo4jClient/GraphClient.cs
As some queries do not require parameters (like a simple MATCH n RETURN n), sending a null instead of an empty dictionary for parameters also make sense. And even if we don't want that behavior we have allow it so far as the library does not throw an ArgumentNullException.
If you do pass on a null dictionary, then the library crashes when the query has been already executed as within `ExecuteCypher` there is a call to `context.Complete()` which receives the `CypherQuery` instance and uses the `DebugQueryText` as the query text that will be sent to the event handler, which in turns parses the parameters and substitute the values within the query where they are being referenced.
First of all, `DebugQueryText` should not be used for this purpose as `context.Complete()` is executed for …
> Allow CypherQuery to have a null value for parameters

- Neo4jClient.Tests/GraphClientTests/FactoryTests.cs
- Neo4jClient.Tests/Neo4jClient.Tests.csproj
- Neo4jClient/Execution/ExecutionConfiguration.cs
- Neo4jClient/GraphClient.cs
- Neo4jClient/GraphClientFactory.cs
- Neo4jClient/IGraphClient.cs
- Neo4jClient/IGraphClientFactory.cs
- Neo4jClient/Neo4jClient.csproj
- Neo4jClient/NeoServerConfiguration.cs
`GraphClient.Connect()` takes optional `NeoServerConfiguration` configuration object now.
The idea behind is to be able to create one single configuration object and have client per request
instead of having one single client per application. Having client per request eliminates current issues with concurrent transactions over single shared client.
**USAGE**
Composition root (structuremap example).
```
public void Register()
{
this.For<NeoServerConfiguration>()
.Use(() => NeoServerConfiguration.GetConfiguration(uri, user, pwd))
.Singleton();
this.For<IGraphClientFactory>()
.Use<GraphClientFactory>()
.Singleton();
}
```
Service level.
```
public class NeoServiceClass
{
private readonly IGraphClientFactory factory;
...
public async Task ExecuteQueryAsync()
{
using (var client = …
```
> NeoServerConfiguration added

- Neo4jClient.Tests/Cypher/CypherFluentQueryAdvancedTests.cs
- Neo4jClient.Tests/Cypher/CypherFluentQueryResultsTests.cs
- Neo4jClient.Tests/Neo4jClient.Tests.csproj
- Neo4jClient/Cypher/CypherFluentQuery.cs
- Neo4jClient/Cypher/CypherFluentQueryAdvanced.cs
- Neo4jClient/Cypher/CypherFluentQuery`Return.cs
- Neo4jClient/Cypher/ICypherFluentQuery.cs
- Neo4jClient/Cypher/ICypherFluentQueryAdvanced.cs
- Neo4jClient/Neo4jClient.csproj
When developing libraries on top of Neo4jClient it can be useful to
expose the low level API to allow control over the return statement
without having to dynamically build up expression trees
> Expose low level return distinct api

- Neo4jClient.Full/Transactions/Neo4jTransactionResourceManager.cs
- Neo4jClient.Full/Transactions/TransactionExecutionEnvironment.cs
- Neo4jClient.Shared/Execution/ExecutionConfiguration.cs
- Neo4jClient.Shared/Transactions/ITransactionExecutionEnvironment.cs
- Neo4jClient.Tests/Neo4jClient.Tests.csproj
- Neo4jClient.Tests/Transactions/TransactionExecutionEnvironmentTests.cs
When there are multiple instances of the graph client library running in
different procesess transactions will not be able to register on account
of the same resource manager id being used. Allowing the user to set the
resource manager id will prevent this problem.
> allow user to set resource manager id

- Neo4jClient.Shared/Cypher/CypherCapabilities.cs
- Neo4jClient.Shared/Cypher/CypherWhereExpressionVisitor.cs
- Neo4jClient.Tests/Cypher/CypherWhereExpressionBuilderTests.cs
HAS() was deprecated since 2.3.x, but it has been removed in 3.0. Any property comparison with a null constant was failing because Neo4jClient was generating it with HAS().
I've added a new cypher capability as well as the necessary changes in the visitors, as well as the unit tests.
> Use EXISTS() instead of HAS() for 3.0

- Neo4jClient.Shared/Cypher/CypherWhereExpressionVisitor.cs
- Neo4jClient.Tests/Cypher/CypherFluentQueryWhereTests.cs
Fluent interface clearly lacked support for Contains and EndsWith and what's worse it also created syntactically incorrect query.
#219
> support Contains and EndsWith on strings in Fluent interface

- Neo4jClient.Shared/Neo4jDriverExtensions.cs
- Neo4jClient.Shared/StatementResultHelper.cs
- Neo4jClient.Tests.Shared/BoltGraphClientTests/Cypher/ExecuteGetCypherResultsTests.cs
- Neo4jClient.Tests.Shared/Extensions/Neo4jDriverExtensionsTests.cs
I detected two serialization bugs for `BoltGraphClient`:
* When a `List` was to be casted into an anonymous typed object, there was a bug where the `ParseAnonymousAsDynamic()` method was splitting all the elements of such list into separate lists containing one element.
* When passing query parameters to `session.Run()` the simple JSON Serialize/Deserialize was not working because when you passed a `Dictionary<string, int[]>` it was being transformed back as `Dictionary<string, JValue>`.
For the first bug the fix is simple: just don't split the list into multiple elements.
For the second bug the fix was more complicated as it is no longer JSON serializing and deserializing but making use of the fact that the bolt driver doesn't care if it receives `object[]` or `List<int>`. So I made the …
> Bolt Serialization/Deserialization Fixes

- Neo4jClient.Shared/BoltGraphClient.cs
- Neo4jClient.Tests/Transactions/BoltQueriesInTransactionTests.cs
Although the reason for `ExecuteMultipleCypherQueriesInTransaction()` was to efficiently send multiple queries in a single HTTP connection/query/disconnect cycle, the recent `BoltGraphClient` marked it as an `InvalidOperationException`, this has already broken compatibility with a call I have in one business project and could potentially affect many more, while this can be easily "simulated."
The "fix" for this is just to effectively setup a transaction and cycle through the queries in such transaction. As `BeginTransaction()` will normally join an existing transaction if there's one, then the semantics remain the same. I have also marked it as `[Obsolete]` within the `BoltGraphClient`
> Backward Compatibility for ExecuteMultipleCypherQueriesInTransaction in BoltGraphClient

- Neo4jClient.Shared/BoltGraphClient.cs
- Neo4jClient.Shared/Serialization/CypherJsonDeserializer.cs
- Neo4jClient.Shared/StatementResultHelper.cs
- Neo4jClient.Tests.Shared/BoltGraphClientTests/Cypher/ExecuteGetCypherResultsTests.cs
Current deserialization fails for the following query:
`MATCH (start:Node) WITH {Node: start, Count: 1} AS Node, start RETURN Node, start`
That is if it includes complex data within the mapping, it fails. 
It includes unit tests.
> Fix Wrong Deserialization for Complex Maps in BoltGraphClient

- Neo4jClient.Shared/Cypher/CypherQuery.cs
- Neo4jClient.Tests.Shared/Cypher/CypherFluentQueryWithParamTests.cs
- Neo4jClient.Tests.Shared/Cypher/CypherQueryTests.cs
The parameter syntax currently used in the DebugQueryText will be deprecated.
https://neo4j.com/docs/developer-manual/3.4-preview/cypher/syntax/parameters/
Added ability to correctly replace either $param or {param} syntax  so DebugQueryText is correctly displayed
> DebugQueryText can process new $param syntax

- Neo4jClient.Shared/Execution/CypherExecutionPolicy.cs
This header doesn't always exist, which would throw an
`KeyNotFoundException`.
Fixes #298
> Don't throw when Location-header is missing

- Neo4jClient.Full.Shared/Transactions/Bolt/BoltTransactionManager.cs
- Neo4jClient.Full.Shared/Transactions/Bolt/BoltTransactionPromotableSinglePhasesNotification.cs
- Neo4jClient.Full.Shared/Transactions/BoltNeo4jTransaction.cs
- Neo4jClient.Full.Shared/Transactions/Neo4jTransactionResourceManager.cs
- Neo4jClient.Full.Shared/Transactions/TransactionManager.cs
- Neo4jClient.Full.Shared/Transactions/TransactionSinglePhaseNotification.cs
- Neo4jClient.Tests.Shared/CultureInfoSetupFixture.cs
- Neo4jClient.Tests.Shared/Extensions/Neo4jDriverExtensionsTests.cs
- Neo4jClient.Tests.Shared/Serialization/CypherJsonDeserializerTests.cs
- Neo4jClient.Tests.Shared/Serialization/UserSuppliedSerializationTests.cs
This fixes several issues:
- Flaky tests
- Cross thread transactions (AsyncLocal for storing transactions)
- SinglePhaseCommit never commiting (only Prepare called, never Commit)
- Commit not commiting (Dispose not called for Neo4j.Driver)
- Commit not commiting (Neo4j.Driver not implementing MarshalByRefObject)
- Transactions getting lost on .NET 4.7.1
I'm not sure about all these changes. In particular the last one is a workaround which we're waiting for an answer from Microsoft if our workaround is sound or subtly broken, ref https://github.com/Microsoft/dotnet-framework-early-access/issues/7#issuecomment-435377965
In order for commit to work on promoted Bolt transactions, we also need a patch in Neo4j.Driver: https://github.com/neo4j/neo4j-dotnet-driver/pull/328
> Fix concurrency issues

- Neo4jClient.Full.Shared/Transactions/Bolt/BoltTransactionManager.cs
- Neo4jClient.Full.Shared/Transactions/ThreadContextHelpers.cs
- Neo4jClient.Full.Shared/Transactions/TransactionManager.cs
We use a single AsyncLocal rather than replacing the global value for each
transaction manager. This makes it possible to run multiple transaction
managers in parallel without clearing each others values.
- Fixes ScopedTransaction is `null`
- ref https://github.com/Readify/Neo4jClient/issues/300
It also seems to have fixed, or at least drastically reduced, the following:
- Neo4j.Driver "The Read method cannot be called when another read operation is pending"
- ref https://github.com/neo4j/neo4j-dotnet-driver/issues/329
- Neo4j.Driver "A blocking operation was interrupted by a call to WSACancelBlockingCall"
- ref https://github.com/neo4j/neo4j-dotnet-driver/issues/329
I'm unsure about the correct behavior in Dispose -- should we really just set the
ScopedTransactions to null? Or should we …
> Only have a single AsyncLocal for the transaction manager

- Neo4jClient.Shared/Serialization/CypherJsonDeserializer.cs
- Neo4jClient.Tests.Shared/BoltGraphClientTests/Cypher/ExecuteGetCypherResultsTests.cs
- Neo4jClient.Tests.Shared/GraphClientTests/Cypher/ExecuteGetCypherResultsTests.cs
When empty result `data: [[ ]]` was encountered, an exception was thrown as
a single result was expected.
> Support empty resultset for the Bolt client

- Neo4jClient.Full.Shared/Transactions/Bolt/BoltTransactionManager.cs
- Neo4jClient.Full.Shared/Transactions/Bolt/BoltTransactionPromotableSinglePhasesNotification.cs
- Neo4jClient.Full.Shared/Transactions/BoltNeo4jTransaction.cs
- Neo4jClient.Full.Shared/Transactions/TransactionExecutionEnvironment.cs
- Neo4jClient.Full.Shared/Transactions/TransactionManager.cs
- Neo4jClient.Shared/BoltGraphClient.cs
- Neo4jClient.Shared/Cypher/CypherFluentQuery.cs
- Neo4jClient.Shared/Cypher/CypherFluentQuery`WithBookmark.cs
- Neo4jClient.Shared/Cypher/CypherQuery.cs
- Neo4jClient.Shared/Cypher/ICypherFluentQuery.cs
- Neo4jClient.Shared/Cypher/QueryWriter.cs
- Neo4jClient.Shared/GraphClient.cs
- Neo4jClient.Shared/Neo4jClient.Shared.projitems
- Neo4jClient.Shared/Neo4jDriverExtensions.cs
- Neo4jClient.Shared/OperationCompletedEventHandler.cs
- Neo4jClient.Shared/Transactions/ITransactionManager.cs
- Neo4jClient.Shared/Transactions/ITransactionalGraphClient.cs
- Neo4jClient.Tests.Shared/BoltGraphClientTests/BoltGraphClientTests.cs
- Neo4jClient.Tests.Shared/BoltGraphClientTests/Bookmarks/BookmarkTests.cs
- Neo4jClient.Tests.Shared/BoltGraphClientTests/Cypher/ExecuteGetCypherResultsTests.cs
- Neo4jClient.Tests.Shared/BoltTestHarness.cs
- Neo4jClient.Tests.Shared/Cypher/CypherFluentQueryWithBookmarkTests.cs
- Neo4jClient.Tests.Shared/Cypher/CypherFluentQueryWithIdentifierTests.cs
- Neo4jClient.Tests.Shared/Neo4jClient.Tests.Shared.projitems
- Neo4jClient.Tests/Transactions/BoltQueriesInTransactionTests.cs
Adds 3 new methods to the `Cypher` fluent query:
* `.WithIdentifier(string)` - which allows you to specifiy an identifier for a query
* `.WithBookmark(string)` - which allows you to execute a query with a specific bookmark
* `.WithBookmarks(params string[])` - Which allows you to execute a query with multiple bookmarks
Changed `OperationCompletedEventArgs` to contain 3 new properties:
* `.LastBookmark` - the last bookmark from the Bolt query
* `.BookmarksUsed` - a list of the bookmarks passed in for the query
* `.Identifier` - the identifier set using `WithIdentifier`
`null` or whitespace to any of these will be ignored, and by default they are all null.
> Adds support for Bookmarks

- Neo4jClient.Full/Neo4jClient.Full.csproj
- Neo4jClient.Full/packages.config
- Neo4jClient.Full452/Neo4jClient.Full452.csproj
- Neo4jClient.Full452/packages.config
- Neo4jClient.Tests/Neo4jClient.Tests.csproj
- Neo4jClient.Tests/packages.config
- Neo4jClient/project.json
Only signed assemblies can be redirected. Signed assemblies has to be signed all the way down. Until #279 is resolved, this change allows us to self-sign neo4jclient so it can be referenced in multiple libraries without causing problems.
> Upgrade Neo4j.Driver and switch from Neo4j.Driver to Neo4j.Driver.Signed

- Neo4jClient.Full/Neo4jClient.Full.csproj
- Neo4jClient.Full/packages.config
- Neo4jClient.Full452/packages.config
- Neo4jClient.nuspec
The System.Net.Http package on NuGet was put there as an OOB update where
Microsoft also tried to add extra functionality for NET Framework developers.
This experiment didn't work, but Microsoft didn't want to pull the package from
NuGet as people would get strange errors.
Microsoft has written a post-mortem on GitHub, ref
https://github.com/dotnet/corefx/issues/17522#issuecomment-338418610
NOTE: I also had to remove NETStandard.Library from NET Framework as that
depends on System.Net.Http from NuGet.
> Use System.Net.Http from NET Framework rather than NuGet

- Neo4jClient.nuspec
Pull #317 updated the Neo4j.Driver version and switched to the signed package.
These changes wasn't reflected in the nuspec file, so the current package at nuget is wrong.
> Set correct package and version for Neo4j.Driver in nuspec

- .gitignore
- Neo4jClient.Full.Shared/BoltGraphClient.cs
- Neo4jClient.Shared/AddressResolver.cs
- Neo4jClient.Shared/BoltGraphClient.cs
- Neo4jClient.Shared/DriverWrapper.cs
- Neo4jClient.Shared/Neo4jClient.Shared.projitems
- Neo4jClient.Shared/UriCreator.cs
- Neo4jClient.Tests.Shared/AddressResolverTests.cs
- Neo4jClient.Tests.Shared/BoltGraphClientTests/BoltGraphClientTests.cs
- Neo4jClient.Tests.Shared/Neo4jClient.Tests.Shared.projitems
- Neo4jClient/BoltGraphClient.cs
In a cluster situation, we could only pass a single URI which meant that should the URI not be contactable, even though other machines in the cluster were, you couldn't connect to it.
With the `Neo4j-Driver` 1.7 release, we could pass in multiple bolt addresses to the Driver to give guides as to where to connect should the main URI be uncontactable. This PR brings that functionality to the `Neo4jClient`.
**This is only for Bolt connections** 
First off, if you're not connecting to a cluster - then don't worry - no code changes!
If you _are_ and you have a rotating DNS type thing set up - then dont worry - no code changes!
If you _do_ want to use it though - there are 2 options available to you:
1. Provide a virtual URI
```
var client = new BoltGraphClient("bolt+routing://virtual.uri", new …
```
> Added support for multiple URIs in the constructor for BoltGraphClient

- Neo4jClient.Shared/Attributes/Neo4jDateTimeAttribute.cs
- Neo4jClient.Shared/BoltGraphClient.cs
- Neo4jClient.Shared/Neo4jClient.Shared.projitems
- Neo4jClient.Shared/Neo4jDriverExtensions.cs
- Neo4jClient.Shared/Serialization/ZonedDateTimeConverter.cs
- Neo4jClient.Shared/StatementResultHelper.cs
- Neo4jClient.Tests.Shared/BoltGraphClientTests/BoltGraphClientTests.cs
- Neo4jClient.Tests.Shared/Neo4jClient.Tests.Shared.projitems
- Neo4jClient.Tests.Shared/Serialization/SerializesDateTimeAsNeoDateTimeTests.cs
- Neo4jClient.Tests.Shared/StatementResultHelperTests.cs
- Neo4jClient.Tests.Shared/TestUtilities.cs
- Neo4jClient/BoltGraphClient.cs
Adding [Neo4jDateTime] to a DateTime/DateTimeOffset will store in Neo4j as a DateTime object instead of a string
> Serialize to Neo4j DateTime instances with Attribute

- Neo4jClient.Shared/Attributes/Neo4jDateTimeAttribute.cs
- Neo4jClient.Shared/BoltGraphClient.cs
- Neo4jClient.Shared/Neo4jClient.Shared.projitems
- Neo4jClient.Shared/Neo4jDriverExtensions.cs
- Neo4jClient.Shared/Serialization/ZonedDateTimeConverter.cs
- Neo4jClient.Shared/StatementResultHelper.cs
- Neo4jClient.Tests.Shared/BoltGraphClientTests/BoltGraphClientTests.cs
- Neo4jClient.Tests.Shared/Neo4jClient.Tests.Shared.projitems
- Neo4jClient.Tests.Shared/Serialization/SerializesDateTimeAsNeoDateTimeTests.cs
- Neo4jClient.Tests.Shared/StatementResultHelperTests.cs
- Neo4jClient.Tests.Shared/TestUtilities.cs
- Neo4jClient/BoltGraphClient.cs
Adding [Neo4jDateTime] to a DateTime/DateTimeOffset will store in Neo4j as a DateTime object instead of a string
> Serialize to Neo4j DateTime instances with Attribute (#327)

- Neo4jClient.Shared/Cypher/CypherWhereExpressionVisitor.cs
- Neo4jClient.Shared/Extensions/ObjectExtensions.cs
- Neo4jClient.Shared/Neo4jClient.Shared.projitems
- Neo4jClient.Tests.Shared/Cypher/CypherFluentQueryWhereTests.cs
- Neo4jClient.Tests.Shared/Extensions/ObjectExtensionTests.cs
- Neo4jClient.Tests.Shared/Neo4jClient.Tests.Shared.projitems
You can now do: 
```
var years = new [] {1980, 1982, 1984};
/*.. stuff ..*/
.Where((Person p) => p.Born.In(years))
```
Which will generate:
`WHERE (p.Born IN {p0})`
> Adding `In` and `NotIn` as extension methods for Object

- Neo4jClient.Tests/Extensions/Neo4jDriverExtensionsTests.cs
- Neo4jClient/Cypher/CypherReturnExpressionBuilder.cs
- Neo4jClient/Neo4jDriverExtensions.cs
- Neo4jClient/Serialization/CommonDeserializerMethods.cs
- Neo4jClient/Serialization/CustomJsonSerializer.cs
- Neo4jClient/StatementResultHelper.cs
Searched for all calls to `JsonConverter.CanConvert(Type)` and added the correct check to `JsonConverter.CanRead` or `JsonConverter.CanWrite`
> Fix #381 - JsonConverters check CanRead/CanWrite before branching

- Neo4jClient.Tests/Cypher/CypherFluentQueryCallTests.cs
- Neo4jClient/Cypher/CypherFluentQuery.cs
- Neo4jClient/Cypher/CypherFluentQuery`Where.cs
- Neo4jClient/Cypher/ICypherFluentQuery.cs
So you can now do:
```
MATCH (x)
CALL { MATCH (y) RETURN COUNT(y) AS c }
RETURN x,c
```
But using functions, so, you can do:
```
var query = new CypherFluentQuery(client)
.Match("(n)")
.Return(n => new {c = n.Count()});
var callQuery = new CypherFluentQuery(client)
.Call(() => query)
.Return(c => c.As<long>());
```
> Add the ability to `CALL` other queries

- Neo4jClient.Tests/StatementResultHelperTests.cs
- Neo4jClient/StatementResultHelper.cs
This PR addresses https://github.com/DotNet4Neo4j/Neo4jClient/issues/417 issue
* Fix typo Deserilizes => Deserializes
* StatementResultHelper.cs is fixed to build valid JSON in case of IRelationship
* New test is provided that emulates the initial problem
> Invalid json using collect over a relationship in bolt client

- Neo4jClient.Tests/BoltGraphClientTests/BoltGraphClientTests.cs
- Neo4jClient.Tests/TestUtilities.cs
- Neo4jClient/BoltGraphClient.cs
- Neo4jClient/Execution/ExecutionConfiguration.cs
- Neo4jClient/Neo4jDriverExtensions.cs
This PR addresses https://github.com/DotNet4Neo4j/Neo4jClient/issues/419 issue
* Introduce property `SerializeNullValues` in `ExecutionConfiguration` class
* Pass new `serializeNullValues` parameter to constructors
* Modify `Neo4jDriverExtensions` to either preserve or skip null values of Objects and Dictionaries depending on congifuration
* Introduce new tests to verify new logic
* Additionally one fix for the `TestUtilities` class to compare dictionaries when left side or right side value is null
> Http and Bolt clients serialize input parameters differently

- Neo4jClient.Tests/Serialization/CypherJsonDeserializerTests.cs
- Neo4jClient/Serialization/CommonDeserializerMethods.cs
This PR is related to the following StackOverflow post: https://stackoverflow.com/questions/69697645/neo4jclient-was-unable-to-deserialize-into-the-object-structure-you-supplied-p
A Neo4j syntax error was not throwing a neo exception meaning the error message did not help debug the problem (missing parenthesis). I've added a deserializer method to catch any neo errors and throw a neo exception so users can easily debug.
> Added improved neo exception handling and error message

- Neo4jClient.Tests/BoltGraphClientTests/Cypher/ExecuteGetCypherResultsTests.cs
- Neo4jClient/ApiModels/Cypher/PathsResultBolt.cs
This PR is to fix issue #431:
- decorated properties of PathsResultBoltRelationship and PathsResultBoltNode with JsonProperty to ensure correct serialization/deserialization when using CamelCasePropertyNamesContractResolver
> Fixed serialization/deserialization of PathsResultBoltRelationship and PathsResultBoltNode

- Neo4jClient.Tests/Cypher/CypherQueryTests.cs
- Neo4jClient/Cypher/CypherQuery.cs
see [https://github.com/DotNet4Neo4j/Neo4jClient/issues/436](url)
> Issue 436 DebugQueryText should serialize object property names without quotes

- Neo4jClient.Tests/BoltGraphClientTests/BoltGraphClientTests.cs
- Neo4jClient.Tests/BoltGraphClientTests/ConnectAsyncTests.cs
- Neo4jClient.Tests/BoltGraphClientTests/Cypher/ExecuteGetCypherResultsTests.cs
- Neo4jClient.Tests/BoltTestHarness.cs
- Neo4jClient.Tests/Neo4jClient.Tests.csproj
- Neo4jClient.Tests/Serialization/SerializesDateTimeAsNeoDateTimeTests.cs
- Neo4jClient.Tests/StatementResultHelperTests.cs
- Neo4jClient/BoltGraphClient.cs
- Neo4jClient/DriverWrapper.cs
- Neo4jClient/GraphClient.cs
- Neo4jClient/Neo4jClient.csproj
- Neo4jClient/Neo4jDriverExtensions.cs
- Neo4jClient/OperationCompletedEventHandler.cs
- Neo4jClient/StatementResultHelper.cs
This means the `BoltGraphClient` will no longer support 4.0 or lower versions of the Neo4j Database - as the Neo4j.Driver doesn't either.
> Upgrading to use Neo4j.Driver v 5.1.0

- Neo4jClient.Tests/BoltGraphClientTests/BoltGraphClientTests.cs
- Neo4jClient.Tests/BoltGraphClientTests/ConnectAsyncTests.cs
- Neo4jClient.Tests/BoltGraphClientTests/Cypher/ExecuteGetCypherResultsTests.cs
- Neo4jClient.Tests/BoltTestHarness.cs
- Neo4jClient.Tests/Neo4jClient.Tests.csproj
- Neo4jClient.Tests/Serialization/SerializesDateTimeAsNeoDateTimeTests.cs
- Neo4jClient.Tests/StatementResultHelperTests.cs
- Neo4jClient/BoltGraphClient.cs
- Neo4jClient/DriverWrapper.cs
- Neo4jClient/GraphClient.cs
- Neo4jClient/IBoltGraphClient.cs
- Neo4jClient/Neo4jClient.csproj
- Neo4jClient/Neo4jDriverExtensions.cs
- Neo4jClient/OperationCompletedEventHandler.cs
- Neo4jClient/StatementResultHelper.cs
I've noticed that the desire to use native datetime instances is growing specially with issue #332 that, although `Neo4jDateTimeAttribute` exists it does not support a comparison with a parameter that is not added through `.WithParam()`. Therefore I took suggestion there to create a "global" (client instance) setting that switches such behavior.
In fact, my PR #275 wished to address this as well (I will continue with this PR as I intend to have a direct serializer instead of still going through creating an intermediate JSON representation).
> Support Neo4j Native datetime Types for Serialization Through Client Setting

- Neo4jClient.Tests/Cypher/CypherFluentQueryDatabaseAdministrationTests.cs
- Neo4jClient/Cypher/CypherCapabilities.cs
- Neo4jClient/Cypher/ICypherFluentQuery`DatabaseAdministration.cs
Fixes #462 
`.Show()` is now in the `ICypherFluentInterface`
To use it would be something like:
```
var names = await client. Cypher
.Show("DATABASES")
.Yield("name")
.Return(name => name.As<string>()).ResultsAsync;
```
> Adds `.Show` to the interface and fixes Cypher Capabilities

- Neo4jClient.Tests/Cypher/CypherWhereExpressionBuilderTests.cs
- Neo4jClient/BoltGraphClient.cs
- Neo4jClient/Cypher/CypherCapabilities.cs
Neo4j 4.4 deprecated EXISTS(), but Neo4j 5 completely removed it. 
I added `Cypher50` capabilities by turning on the `SupportsNullComparisonsWithIsOperator` capability.
> Added Cypher50 capabilities for Neo4j5 null comparison

- Neo4jClient/Cypher/CypherCapabilities.cs
The `SupportsRuntime` was not set in most static `CypherCapabilities` instances. This causes `boltClient.Cypher.Runtime(CypherRuntime.Parallel)` to throw an exception:
```
System.InvalidOperationException: 'runtime=' not supported in Neo4j versions older than 3.5
at Neo4jClient.Cypher.CypherFluentQuery.Runtime(String runtime)
at Neo4jClient.Cypher.CypherFluentQuery.Runtime(CypherRuntime runtime)
...
```
For now, we fixed it in our own code by just setting the `CypherCapabilities.SupportsRuntime` before using the `Runtime(...)`:
```cs
/// <inheritdoc />
public async Task<ICypherFluentQuery> FluentReadQuery()
{
var boltClient = await this.ConnectedBoltGraphClient();
boltClient.CypherCapabilities.SupportsRuntime = true; // <--- the temporary fix
var cypherFluentQuery = …
```
> Also set `SupportsRuntime `
